### ISSUE TITLE
Unsure how to set <hummingbird-command-options>

### ISSUE THREAD

**Issue by Snuffy2** [fschaeck/AirVPN-hummingbird-docker#1]
I know this is a dumb question, but I'm not sure how to set the options correctly. I don't know how to translate <hummingbird-command-options> into a run or docker-compose command. Thanks and sorry.

These aren't working:
```
sudo docker run -it --cap_add=NET_ADMIN --cap_add=SYS_MODULE -v /lib/modules:/lib/modules:ro -v /mnt/data:/data -v /docker/appdata/airvpn-hummingbird:/config --device /dev/net:/dev/net fschaeckermann/airvpn-hummingbird <hummingbird-command-options> = /config/airvpn.ovpn
```

```
version: '3.7'
services:
  airvpn-hummingbird:
    container_name: airvpn-hummingbird
    restart: unless-stopped
    logging:
      driver: json-file
    volumes:
      - /docker/appdata/airvpn-hummingbird:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data:/data
    environment:
      - <hummingbird-command-options>='/config/airvpn.ovpn'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - '/dev/net:/dev/net'
    image: fschaeckermann/airvpn-hummingbird
```

**Comment by Snuffy2** [comment]
fschaeck has updated the Readme and I was able to sort out how to do this:

```
sudo docker run -ti --cap-add=NET_ADMIN --cap-add=SYS_MODULE -v /lib/modules:/lib/modules:ro --device /dev/net:/dev/net -v /docker/appdata/airvpn-hummingbird/airvpn.ovpn:/config.ovpn:ro fschaeckermann/airvpn-hummingbird /config.ovpn
```

```
  airvpn-hummingbird:
    container_name: airvpn-hummingbird
    restart: unless-stopped
    logging:
      driver: json-file
    volumes:
      - /docker/appdata/airvpn-hummingbird:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/New_York
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - '/dev/net:/dev/net'
    image: fschaeckermann/airvpn-hummingbird
    command:
      - /config/airvpn.ovpn
```
